[package]
name = "shutl"
version = "0.0.3"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive", "string"] }
clap_complete = { version = "4.5", features = ["unstable-dynamic"] }
dirs = "6.0"

[dev-dependencies]
tempfile = "3.8"
