name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install cargo-release
      run: cargo install cargo-release
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get the current version from Cargo.toml
        CURRENT_VERSION=$(grep '^version' Cargo.toml | cut -d '"' -f 2)
        
        # Create a new tag
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git tag -a "v${CURRENT_VERSION}" -m "Release v${CURRENT_VERSION}"
        git push origin "v${CURRENT_VERSION}"
        
        # Create GitHub release
        gh release create "v${CURRENT_VERSION}" \
          --title "Release v${CURRENT_VERSION}" \
          --notes "Release v${CURRENT_VERSION}" \
          --draft \
          --prerelease 
