name: Semantic Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  semantic:
    name: Check Semantic PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}