name: Semantic Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  semantic:
    name: Check Semantic PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semantic Pull Request
        uses: amannn/action-semantic-pull-request@v4
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore